name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Set up Java 25
        uses: actions/setup-java@3a3fa871871216b3f7f8d6896265005d95d105fd # v4.4.0
        with:
          distribution: 'temurin'
          java-version: '25'

      - name: Cache Maven Dependencies
        uses: actions/cache@1bd1e3253bdc8e1684399d10c3f7107419388280 # v4.1.2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Run Verification (Build & Test)
        run: ./mvnw clean verify
